### ISSUE TITLE
Task: Drop controller unit tests

### ISSUE THREAD

**Issue by andreaswolf** [FriendsOfTYPO3/tea#1479]
## Goal

Testing controllers with isolated unit tests requires lots of mocking of stuff that is not under the control of the individual extension author (repositories that rely on Extbase's base repository, the view, the response, …). Therefore, the tests are hard to write and easily break when doing an upgrade. Additionally, mocking stuff you don't own is an antipattern.

Thus, the required effort makes them expensive, while not being very valuable. Presenting this as a best practice nonetheless may deter people from writing tests at all. Therefore, I consider that harmful and would strongly vote to only present good testing practices within this extension.

## Acceptance Criteria
- [ ] All unit tests that test controllers have been removed

**Comment by oliverklee** [comment]
I disagree (and you probably already know that we have two different opinions on this :wink:) on the point that unit tests for controllers are harmful. I find unit tests for controllers helpful to check that the "plumbing has been done correctly".

Particularly, I think that removing unit tests for functionality that is not covered yet by functional tests is not helpful.

Would you be willing to contribute controller functional tests for functionality that currently is only covered by unit tests? (This would allow us to reduce the unit tests any maybe remove some of them altogether if we can check the "plumbing" in functional tests as well.)

**Comment by oliverklee** [comment]
Let me make some things clear on a higher level:

- This extension is an opinionated collection of what the Best Practices Team (not just me personally) recommends as best practices for extensions based on our expertise, our research and on trying things out. This extension does not strive to represent what "the rest of the community" does, even if we try to stick close to what the Core does.
- GitHub tickets or discussions are not the place where the Best Practices Team comes to decisions. That's during the calls. As I understand that this ticket has turned into a discussion, I will close it.
- I already wrote that I'd be willing to replace the controller unit tests with functional tests. You're welcome to contribute to those to help things forward. (That we don't have more functional tests for controllers is not because we don't want them or don't consider them to be helpful, but because someome (TM) needs to put time into that.) I'm not okay with removing the current unit tests without replacement (which is what this ticket initially was about as I understand it).
