### ISSUE TITLE
Fix spelling of TSconfig folder

### ISSUE THREAD

**Issue by liayn** [FriendsOfTYPO3/tea#923]
It was decided how to spell the TSconfig folder. This ext be a good example, hence lets adapt.

Sources:
https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/Glossary.html
https://review.typo3.org/c/Packages/TYPO3.CMS/+/77725

**Comment by liayn** [comment]
Relates to https://github.com/FriendsOfTYPO3/tea/issues/522

**Comment by lukaszuznanski** [comment]
@brotkrueml is bringing up comment from your documentation PR. How can we proceed here? Which version is correct?

**Comment by liayn** [comment]
I was told via Slack, that the Glossary is the way to go.

**Comment by brotkrueml** [comment]
Yore used `TsConfig` in v11: https://github.com/TYPO3/typo3/tree/11.5/typo3/sysext/backend/Configuration/TsConfig/Page/Mod/Wizards

Since v12 `TsConfig` folder is gone in favour of `Configuration/page.tsconfig`.

**Comment by lukaszuznanski** [comment]
@DanielSiepmann @oliverklee what are your opinions on that?

**Comment by DanielSiepmann** [comment]
I'm probably not a big help here. But let me provide my insights and opinions.

I remember there was a discussion on Slack about the topic. The v12 core way doesn't follow the decisions on decisions.typo3.org or the existing docs, but they didn't want to make another change in that area …
Also autoloading `/page.tsconfig` doesn't say anything about the folder. You might have a large amount of page tsconfig, e.g. within sitepackages. Therefore, a convention for a folder should still exist. Files from the folder can be included within page.tsconfig.

I'd not care too much about the `glossary` as this has nothing to do with filesystem, but how to write things out in text content.

Right now https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/FileStructure/Configuration/Index.html and https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/FileStructure/Configuration/TsConfig/Index.html have different conventions. We should not decide within our team, but wait for a clear decision from core and a streamlined structure within docs. https://decisions.typo3.org/t/file-endings-for-typoscript-and-tsconfig-files-results/71 contains the results from the original decisions. I'm not too much into detail and don't know why this topic is raising again instead of sticking to the decision …

**Comment by oliverklee** [comment]
> We should not decide within our team, but wait for a clear decision from core and a streamlined structure within docs

I agree.

**Comment by liayn** [comment]
The glossary and the decision actually match.

I don't care too much what's being used inside the core at the moment. This project should cater as a good practice for *new* stuff, so my goal is to have this correct.

(and yes, the docs shall be adjusted as well to match the decision; Thanks for the hint to the decision btw.)

**Comment by DanielSiepmann** [comment]
Please help me with:

> The glossary and the decision actually match.

There was no final result on the folder structure. And I can't find the follow-up voting.

For me the glossary says "page TSconfig" and doesn't have user TSconfig yet.
The most votes say `Configuration/TsConfig/Page` and `Configuration/TsConfig/User`.

So they do not match on my opinion. Which is fine as one is for text and the other for file system.
They don't match in TSc vs TsC and they do not match in the order being TsConfig followed by Page from result while having page in front of TSconfig within glossary.

I just want to gain the same understanding here.

**Comment by liayn** [comment]
> There was no final result on the folder structure. And I can't find the follow-up voting.

Oh forgive me, I missed this part of Bennis summary:

>  folder structure default naming is not a clear result

I tend to close this issue here then.

**Comment by brotkrueml** [comment]
> Right now https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/FileStructure/Configuration/Index.html and https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/FileStructure/Configuration/TsConfig/Index.html have different conventions. We should not decide within our team, but wait for a clear decision from core and a streamlined structure within docs. 

I created a PR to streamline the wording: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/3575
